/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 1.3.39
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

namespace OSGeo.GDAL {

public enum ViewshedOutputType {
  GVOT_NORMAL = 1,
  GVOT_MIN_TARGET_HEIGHT_FROM_DEM = 2,
  GVOT_MIN_TARGET_HEIGHT_FROM_GROUND = 3
}

}
